### ISSUE TITLE
Credit/attribution notice

### ISSUE THREAD

**Issue by thosakwe** [mortea15/fluttersteem#2]
Hi, I noticed a great deal of similarity between this package and my earlier one: https://github.com/thosakwe/instagram_dart

This is fine. Such is the nature of open-source.

What I do ask, however, is that you put some sort of mention or reference to `instagram_dart`, so that if there are underlying bugs caught here, they can be fixed both in `fluttersteem` and `instagram_dart`. The MIT License simply asks that you reference the original when producing a copy.

Thanks.

**Comment by netr0m** [comment]
That is absolutely correct! I pushed an update just now which credits your repository. it can be found in the readme.
Thanks for reminding me, and thank you for open-sourcing your code :)
